### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by cmueller79** [tribe29/salt-checkmk#4]
Hi im testing your salt Project local 
but get error  by testing

`root@CT106:/srv/formulas/salt-checkmk# salt-call --local state.apply omd
[ERROR   ] State 'omd.site_present' was not found in SLS 'omd'
Reason: 'omd.site_present' is not available.

local:
----------
          ID: ensure-omd-site-demo01-present
    Function: omd.site_present
        Name: demo01
      Result: False
     Comment: State 'omd.site_present' was not found in SLS 'omd'
              Reason: 'omd.site_present' is not available.
     Changes:   
----------
`

TEST OK it works now for me

**Comment by PhilippLemke** [comment]
Hi,
it seems that your salt-minion is not aware of omd custom state/execution
modules.
You can force the synchronization with "salt-call --local
saltutil.sync_all".
Have you tried the quickstart masterless example? The Sync should be done
automatically there.

Philipp


Am So., 1. Mai 2022 um 22:43 Uhr schrieb cmueller79 <
***@***.***>:

**Comment by PhilippLemke** [comment]
👍
